os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - curl -sL https://gist.githubusercontent.com/czechboy0/77c97b4ced37b512d1a2/raw/aa5ec6e29ccab3103f5e2efa1a69663626225699/redis-local-install.sh | bash
  - curl -sL https://gist.githubusercontent.com/czechboy0/6539d0586a2c080e403c/raw/66eae4e588fd43f00d85ca768db46f7ceae89566/swiftenv-install.sh | bash
script:
  - . ~/.swiftenv/init
  - swift build
  - make redis-start
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make xctest; fi
  - .build/debug/RedbirdExample
notifications:
  email:
    on_success: never
    on_failure: change



