version: 2

jobs:
  11-bionic:
    docker:
      - image: swift:5.0-bionic
      - image: redis:5
        name: redis
    steps:
      - checkout
      - run: swift build
      - run: swift test
  bionic-release:
    docker:
      - image: swift:5.0-bionic
    steps:
      - checkout
      - run: swift build -c release
workflows:
  version: 2
  tests:
    jobs:
      - 11-bionic
      - bionic-release

