version: '2'

services:
  tests:
    build: 
      context: .
      dockerfile: tests.Dockerfile
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
      - REDIS_HOSTNAME_2=redis2
      - REDIS_PORT_2=6379
    depends_on: [redis, redis2]

  redis:
    image: redis
    ports:
      - 6379:6379

  redis2:
    image: redis
    ports:
      - 6380:6379

