name: test
on:
- pull_request
jobs:
  xenial:
    container: 
      image: vapor/swift:5.1-xenial
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
      env:
        REDIS_HOSTNAME: redis
  bionic:
    container: 
      image: vapor/swift:5.1-bionic
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test --enable-test-discovery --sanitize=thread
      env:
        REDIS_HOSTNAME: redis
