name: test
on: { pull_request: {}, push: {} }

jobs:
  getcidata:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.output.outputs.environments }}
    steps:
      - id: output
        run: |
          envblob="$(curl -fsSL https://raw.githubusercontent.com/vapor/ci/main/pr-environments.json | jq -cMj '.')"
          echo "::set-output name=environments::${envblob}"


  test-redis:
    needs: getcidata
    strategy:
      fail-fast: false
      matrix:
        env: ${{ fromJSON(needs.getcidata.outputs.environments) }}
        include:
          - services: {}
            redis_url_1: redis://localhost:6379
            redis_url_2: redis://localhost:6380
          - env: { os: ubuntu-latest }
            services: 
              redis: { image: redis, ports: [ '6379:6379' ] } 
              redis2: { image: redis, ports: [ '6380:6379' ] } 
            redis_url_1: redis://localhost:6379
            redis_url_2: redis://localhost:6380
    runs-on: ${{ matrix.env.os }}
    container: ${{ matrix.env.image }}
    services: ${{ matrix.services }}
    steps: 
      - name: Select toolchain
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: ${{ matrix.env.toolchain }}
        if: ${{ matrix.env.toolchain != '' }}
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up Redis servers via Homebrew
        if: ${{ matrix.env.toolchain != '' }}
        run: brew install redis && redis-server .github/redis1.conf && redis-server .github/redis2.conf 

      - name: Set up Redis cli servers via apt-get
        if: ${{ matrix.env.toolchain == '' }}
        run: apt-get install -y redis
      - name: Test Redis 1 connection
        run: redis-cli -u ${{ matrix.redis_url_1 }} INFO
      - name: Test Redis 2 connection
        run: redis-cli -u ${{ matrix.redis_url_2 }} INFO
      - run: cat .github/workflows/test.yml
      - name: Run tests with Thread Sanitizer
        timeout-minutes: 20
        run: swift test --enable-test-discovery --sanitize=thread
        env:
          REDIS_URL_1: ${{ matrix.redis_url_1 }}
          REDIS_URL_2: ${{ matrix.redis_url_2 }}
