name: test
on: { pull_request: {} }

jobs:
  getcidata:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.output.outputs.environments }}
    steps:
      - id: output
        run: |
          envblob="$(curl -fsSL https://raw.githubusercontent.com/vapor/ci/main/pr-environments.json | jq -cMj '.')"
          echo "::set-output name=environments::${envblob}"


  test-redis:
    needs: getcidata
    strategy:
      fail-fast: false
      matrix:
        env: ${{ fromJSON(needs.getcidata.outputs.environments) }}
        include:
          - services: {}
            redis_host: localhost
          - env: { os: ubuntu-latest }
            services: { redis: { image: redis, ports: [ '6379:6379' ] } }
            redis_host: redis
    runs-on: ${{ matrix.env.os }}
    container: ${{ matrix.env.image }}
    services: ${{ matrix.services }}
    steps: 
      - name: Select toolchain
        uses: maxim-lobanov/setup-xcode@v1.2.1
        with:
          xcode-version: ${{ matrix.env.toolchain }}
        if: ${{ matrix.env.toolchain != '' }}
      - name: Set up Redis server via Homebrew
        if: ${{ matrix.env.toolchain != '' }}
        run: brew install redis && brew services start redis
      - name: Check out Redis
        uses: actions/checkout@v2
      - name: Run tests with Thread Sanitizer
        timeout-minutes: 20
        run: swift test --enable-test-discovery --sanitize=thread
        env:
          REDIS_HOSTNAME: ${{ matrix.redis_host }}
